### ISSUE TITLE
Think about allowing to have multiple mocoWriter

### ISSUE THREAD

**Issue by tyx** [rezzza/moco-behat-extension#3]
If an application need to mock different hostname, it would be impossible currently.

Solutions : 
- Move out hostname from behat config and let people configure it at runtime when using `MocoWriter`
- Configure multiple hostname in behat config, create as many MocoWriter as hostnames, and find a way to allow people injecting the good one in their context

**Comment by tyx** [comment]
In fact I was totally wrong. `hostname` is just used for heath check purpose. So we should consider to refactore that part to allow multiple health_check

**Comment by tyx** [comment]
So we could imagine change `MocoWriter` to add a collections of `hostname:port` indexed by name : 
```
default:
    extensions:
        Rezzza\MocoBehatExtension\MocoExtension:
            json_file: features/fixtures.yml
            hosts:
                my_first_mock: { hostname: http://coucou.hibou, port: 2113 }
                my_other_mock: { hostname: http://coucou.filou, port: 2113 }
```

Then the `MocoWriter::mockHttpCall` should be changed to receive the name of the hosts targeted by this call. We should continue to enqueue the httpCall but also the hosts.

And add a BeforeStep hook, that will watch for the first `When` step and automatically call `writeForMoco` and wait for all mocos we queued

Big BC break, that would lead to v2.0
